doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_mysql'
    server_version: '8.0'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: 'utf8mb4_unicode_ci'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src'
        prefix: 'App'
        alias: App
