framework:
  rate_limiter:
    login:
      policy: 'sliding_window'
      limit: 5
      interval: '1 minute'
    client_token:
      policy: 'sliding_window'
      limit: 10
      interval: '1 minute'

