blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: mailto:thavarshan@gmail.com
    about: Please report security vulnerabilities privately via email
  - name: Documentation
    url: https://github.com/Thavarshan/orthrus/blob/main/README.md
    about: Check the README for API documentation and setup instructions
  - name: Contributing Guidelines
    url: https://github.com/Thavarshan/orthrus/blob/main/CONTRIBUTING.md
    about: Read our contributing guidelines before submitting issues or PRs