name: Deploy (Forge)

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Forge Deployment
        env:
          FORGE_DEPLOY_HOOK_URL: ${{ secrets.FORGE_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$FORGE_DEPLOY_HOOK_URL" ]; then
            echo "FORGE_DEPLOY_HOOK_URL is not set. Add it in repo Settings > Secrets and variables > Actions." >&2
            exit 1
          fi
          curl -fsSL -X POST "$FORGE_DEPLOY_HOOK_URL"
